language: php
sudo: false
php:
    - 8.0
cache:
    directories:
        - $HOME/.composer/cache
addons:
    sonarcloud:
        organization: "quillstack"
        token:
            secure: "TEKHvLtngOubhCyTGFd/aodnZ1ZTMMoeFaR7zdsBi5q8I7uRND3XgQZC+5jsWgRyn49Nt/y6k1sMK6TphMpHFhVSzGs9n4RelYBPuHn8379Y+LNeKIU8n+H/dv9Uj9UvcG2K3qJhCK2UquC/1KlfajFSxTLtUr4pAG1g3EjKe5pFk9xJzoKih4SoOCtwt+RpnjzmYyJx2P6M9X/xhimoEaHz8IAtex8t6UK5lFSvKjoqjves23StdCgRBAHmFSxY8BQgsiZsqcVFG6kBsCfUanVodqZ2qpSQ6t4HS5Bv1YlHS5pp7API311PPvEC5Qfk204GcWVgNkaCpujYJuwi+u21b/7yjgdSl47pJmiKrfw7GCS4AxqtSrcO29r1qkBUUK7Nx4qOafpIMfFtPO7W2wU6s59mmTcOop9K9CaxaIsAeYMkGj2PRHKr/BLTSsVEFUcOBZ0l2qQoPoLdyTUIAEDJ409j3lvrUruxLV5JPlAidC4wH5Mwp4wPxS8YiZsA2pFzmQ70u1wwQkZ3wu39MVYzMlzGy37KUwtHNKq6mkYIDozVoByQtZkOjqgEgF+FJbQZGMxZQvyB0naRF5R63T6cXZH5FNgkEG1mYKjiaEXypKhPMKp7dGdPmqKJqigiT6iEnAxl6NWouWkdvDJuyANdTPUJnlEF6C4zJxax6qo="
git:
    depth: false
install: composer update --no-interaction --no-suggest --no-progress
script:
    - phpdbg -qrr ./vendor/bin/unit-tests
    - sonar-scanner
